import enum


class QueryDeviceConfigFlags(enum.IntEnum):
    ALL_PATHS = 0x00000001
    ONLY_ACTIVE_PATHS = 0x00000002
    DATABASE_CURRENT = 0x00000004


class DisplayConfigDeviceInfoType(enum.IntEnum):
    GET_SOURCE_NAME = 1
    GET_TARGET_NAME = 2
    GET_TARGET_PREFERRED_MODE = 3
    GET_ADAPTER_NAME = 4
    SET_TARGET_PERSISTENCE = 5
    GET_TARGET_BASE_TYPE = 6
    FORCE_UINT32 = 0xFFFFFFFF
